import Head from 'next/head'
import Image from 'next/image'
import { Geist, Geist_Mono } from 'next/font/google'
import MyNav from '@/components/MyNav'
import 'bootstrap/dist/css/bootstrap.min.css'
import Hero from '@/components/Hero'
import OllamaChat from '@/components/ollama'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <MyNav />
        <Hero />
        <Footer />
      </div>
    </>
  )
}
